config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses
	root 'static_pages#homepage'
	# get 'static_pages/homepage'
	# get 'static_pages/privacy'
	get 'privacy', to: 'static_pages#privacy'
	get 'static_pages/activity'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	validates :title, presence: true
	validates :description, presence: true, length: { :minimum => 5 }
	belongs_to :user
	def to_s
		title
	end
	has_rich_text :description

	include PublicActivity::Model
  	tracked owner: Proc.new{ |controller, model| controller.current_user }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def to_s
  	email
  end
  has_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	# add to the activity tracker on the App Controller level
	include PublicActivity::StoreController
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def homepage
  end

  def privacy
  end
  def activity
  	@activities = PublicActivity::Activity.all  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/courses/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.label :description
    = f.rich_text_area :description

  .form-actions
    = f.button :submit

app/views/courses/edit.html.haml
%h1 Editing Arts Course

= render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
%h1 Listing Arts Classes

%table.table
  %thead
    %tr
      %th Title
      %th Description
      %th Email
      %th
      %th

  %tbody
    - @courses.each do |course|
      %tr
        %td= course.title
        %td= course.description
        %td= course.user
        %td= link_to 'Show', course
        %td= link_to 'Edit', edit_course_path(course)
        %td= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Course', new_course_path

app/views/courses/new.html.haml
.container
  %h1 New Arts Course

  = render 'form'

  = link_to 'Back', courses_path

app/views/courses/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @course.title
%p
  %b Description:
  = @course.description

= link_to 'Edit', edit_course_path(@course)
\|
= link_to 'Back', courses_path

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} x
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navbar.html.haml
- if current_user
  = current_user.email
  = link_to 'Settings', edit_user_registration_path
  = link_to 'Sign Out', destroy_user_session_path, method: :delete
- else
  .container
    = link_to 'Join Now', new_user_registration_path
    = link_to 'Login', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Product
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    = render 'layouts/messages'
    / %p.notice= notice
    / %p.alert= alert
    = yield

app/views/static_pages/activity.html.haml
%h1 Activity Feed
- @activities.each do |activity|
  .row
  = activity.id
  = activity.trackable_type
  = activity.trackable_id
  = link_to activity.trackable, activity.trackable
  = activity.key
  = activity.parameters
  = activity.owner

app/views/static_pages/homepage.html.haml
.container
  %h1 Welcome to Ardun
  %p A place the performing arts students to find and connect with teachers
  = link_to "Privacy", privacy_path

  = link_to courses_path, class: 'btn' do
    .fa.fa-book
    Arts

app/views/static_pages/privacy.html.haml
.container
  %h1 Privacy at Ardun
  %p We will not sell your data
  = link_to "Home Page", root_path, class:"btn btn-lg"